export const testMenu = [
  {
    code: "TPC",
    name: "Thyroid Function Test (T3, T4, TSH) - SRL Mohali",
    mrp: "450",
    method: "CLIA",
    tat: "6-12 Hours",
    sample: "Serum",
    preparation: "8 Hours Fasting Required.",
  },
  {
    code: "LIPID",
    name: "Advanced Lipid Profile (Cardiac Risk) - Agilus Diagnostics",
    mrp: "730",
    method: "Photometric",
    tat: "12-24 Hours",
    sample: "Serum",
    preparation: "8-10 hours fasting.",
  },
  {
    code: "HBA1C",
    name: "HbA1c - Diabetes Monitoring in Mohali",
    mrp: "425",
    method: "HPLC",
    tat: "6-12 Hours",
    sample: "Blood",
    preparation: "None required.",
  },
  {
    code: "LFT",
    name: "Liver Function Test (LFT) - Best Lab in Mohali",
    mrp: "630",
    method: "Photometric",
    tat: "12-24 Hours",
    sample: "Serum",
    preparation: "None required.",
  },
  {
    code: "KFT",
    name: "Kidney Function Test (KFT) - Agilus Mohali",
    mrp: "730",
    method: "Photometric",
    tat: "12-24 Hours",
    sample: "Serum/Urine",
    preparation: "None required.",
  },
  {
    code: "VITD",
    name: "Vitamin D (25-OH) - Bone Health Test",
    mrp: "900",
    method: "CLIA",
    tat: "6-8 Hours",
    sample: "Serum",
    preparation: "None required.",
  },
  {
    code: "VIT12",
    name: "Vitamin B12 - Nerve Health Test",
    mrp: "1350",
    method: "CLIA",
    tat: "6-8 Hours",
    sample: "Serum",
    preparation: "None required.",
  },
  {
    code: "DIAB",
    name: "Diabetes Screening Panel - SRL Mohali",
    mrp: "500",
    method: "Photometric",
    tat: "6-12 Hours",
    sample: "Blood",
    preparation: "Fasting required.",
  },
  {
    code: "AG-FULL-01",
    name: "Agilus Best Full Body Checkup | Mohali",
    mrp: "3099",
    method: "Comprehensive Wellness Panel",
    tat: "24 Hours",
    sample: "Blood/Urine (Free Home Collection)",
    preparation: "10-12 hours fasting required.",
  },
  {
    code: "FBS-PP",
    name: "SRL/Agilus Diabetes Monitoring Package | Tricity",
    mrp: "599",
    method: "HbA1c & Glucose Analysis",
    tat: "12 Hours",
    sample: "Blood (Home Collection Available)",
    preparation: "Depands PP, FBS, Random.",
  },
  {
    code: "Free",
    name: "Agilus Advanced Thyroid Profile (FT3, FT4, TSH)",
    mrp: "750",
    method: "CLIA",
    tat: "12-24 Hours",
    sample: "Blood (Home Collection Available)",
    preparation: "Early morning sample preferred.",
  },
  {
    code: "AG-LIPID-01",
    name: "SRL Heart Health & Lipid Profile",
    mrp: "450",
    method: "Spectrophotometry",
    tat: "24 Hours",
    sample: "Blood (Home Collection Available)",
    preparation: "10-12 hours fasting recommended.",
  },
  {
    code: "AG-VIT-01",
    name: "Agilus Vitamin D & B12 Combo Test",
    mrp: "2200",
    method: "CLIA",
    tat: "24-48 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-CBC-01",
    name: "SRL/Agilus Complete Blood Count (CBC)",
    mrp: "240",
    method: "Automated Hematology Analyzer",
    tat: "12 Hours",
    sample: "Blood (Home Collection Available)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-KFT-01",
    name: "Agilus Kidney Function Test (KFT)",
    mrp: "730",
    method: "Automated Biochemistry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-LFT-01",
    name: "SRL Liver Function Test (LFT)",
    mrp: "630",
    method: "Automated Biochemistry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "10-12 hours fasting for best results.",
  },
];
