export const testMenu = [
  {
    code: "THYR",
    name: "Thyroid Function Test (T3, T4, TSH) - SRL Mohali",
    mrp: "700",
    method: "CLIA",
    tat: "6-12 Hours",
    sample: "Serum",
    preparation: "None required.",
  },
  {
    code: "LIPID",
    name: "Advanced Lipid Profile (Cardiac Risk) - Agilus Diagnostics",
    mrp: "900",
    method: "Photometric",
    tat: "12-24 Hours",
    sample: "Serum",
    preparation: "10-12 hours fasting.",
  },
  {
    code: "HBA1C",
    name: "HbA1c - Diabetes Monitoring in Mohali",
    mrp: "600",
    method: "HPLC",
    tat: "6-12 Hours",
    sample: "Blood",
    preparation: "None required.",
  },
  {
    code: "LFT",
    name: "Liver Function Test (LFT) - Best Lab in Mohali",
    mrp: "850",
    method: "Photometric",
    tat: "12-24 Hours",
    sample: "Serum",
    preparation: "Overnight fasting recommended.",
  },
  {
    code: "KFT",
    name: "Kidney Function Test (KFT) - Agilus Mohali",
    mrp: "800",
    method: "Photometric",
    tat: "12-24 Hours",
    sample: "Serum/Urine",
    preparation: "None required.",
  },
  {
    code: "VITD",
    name: "Vitamin D (25-OH) - Bone Health Test",
    mrp: "1200",
    method: "CLIA",
    tat: "24 Hours",
    sample: "Serum",
    preparation: "None required.",
  },
  {
    code: "VIT12",
    name: "Vitamin B12 - Nerve Health Test",
    mrp: "1000",
    method: "CLIA",
    tat: "24 Hours",
    sample: "Serum",
    preparation: "None required.",
  },
  {
    code: "DIAB",
    name: "Diabetes Screening Panel - SRL Mohali",
    mrp: "500",
    method: "Photometric",
    tat: "6-12 Hours",
    sample: "Blood",
    preparation: "Fasting required.",
  },
  {
    code: "AG-FULL-01",
    name: "Agilus Platinum Full Body Checkup | Mohali",
    mrp: "2999",
    method: "Comprehensive Wellness Panel",
    tat: "24 Hours",
    sample: "Blood/Urine (Free Home Collection)",
    preparation: "10-12 hours fasting required.",
  },
  {
    code: "AG-DIAB-01",
    name: "SRL/Agilus Diabetes Monitoring Package | Tricity",
    mrp: "899",
    method: "HbA1c & Glucose Analysis",
    tat: "12 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-THYR-01",
    name: "Agilus Advanced Thyroid Profile (T3, T4, TSH)",
    mrp: "650",
    method: "CLIA",
    tat: "12-24 Hours",
    sample: "Blood (Free Home Collection Available)",
    preparation: "Early morning sample preferred.",
  },
  {
    code: "AG-LIPID-01",
    name: "SRL Heart Health & Lipid Profile",
    mrp: "550",
    method: "Spectrophotometry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "10-12 hours fasting recommended.",
  },
  {
    code: "AG-VIT-01",
    name: "Agilus Vitamin D & B12 Combo Test",
    mrp: "1400",
    method: "CLIA",
    tat: "24-48 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-CBC-01",
    name: "SRL/Agilus Complete Blood Count (CBC)",
    mrp: "350",
    method: "Automated Hematology Analyzer",
    tat: "12 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-KFT-01",
    name: "Agilus Kidney Function Test (KFT)",
    mrp: "700",
    method: "Automated Biochemistry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "No specific prep required.",
  },
  {
    code: "AG-LFT-01",
    name: "SRL Liver Function Test (LFT)",
    mrp: "750",
    method: "Automated Biochemistry",
    tat: "24 Hours",
    sample: "Blood (Free Home Collection)",
    preparation: "10-12 hours fasting for best results.",
  },
];
